.\" $Id: athrun.1,v 1.1 2000-03-25 19:05:26 ghudson Exp $
.\"
.\" Copyright 2000 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.TH ATHRUN 1 "18 March 2000"
.SH NAME
athrun \- Run a program from an Athena locker
.SH SYNOPSIS
.B athrun \fIlockername\fP [\fIprogname\fP] [\fIargs\fP...]
.SH DESCRIPTION
.B athrun
provides a convenient and robust way for users to run a program from
a specific Athena locker.  If
.I progname
is not specified, it is assumed to be the same as the locker name.
.SH "SEE ALSO"
.BR attachandrun (1)
.SH AUTHOR
Greg Hudson, MIT Information Systems
.br
Copyright 2000 by the Massachusetts Institute of Technology.
