.\" $Id: attachandrun.1,v 1.2 2006-06-26 05:22:20 ghudson Exp $
.\"
.\" Copyright 1997 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\"
.TH ATTACHANDRUN 1
.SH NAME
attachandrun \- attach a filesystem and run a program from it

.SH SYNOPSIS
attachandrun [--check] locker program argv0 [argv1 ...]

.SH DESCRIPTION
\fIattachandrun\fR combines the operations of attaching a locker,
locating its binary directory, and executing a program out of that
directory. Running a program via \fIattachandrun\fR should be
indistinguishable from running it out of its locker by hand. A typical
``attach and run'' script would look like:

.nf
    #!/bin/sh
    exec /bin/athena/attachandrun moira blanche "$0" "$@"
.fi

If you specify the \fI--check\fR option, \fIattachandrun\fR will check
for the existence of the binary but not actually run it. (In this
case, you don't need to specify any argv elements.) It will exit with
status 0 if the binary exists, or 1 if it does not. Note that a
successful exit status does not necessarily mean that attempting to
run the binary will succeed: it indicates only that the file exists.

.SH "SEE ALSO"
attach(1), athdir(1)

.SH AUTHORS
Craig Fields, MIT Information Systems
Dan Winship, MIT Information Systems
.PP
Copyright 1998 Massachusetts Institute of Technology
